---
title: "Procesamiento de datos - ejemplo"
---

# Descripción general

Este código procesa los datos originales y genera un archivo con la información necesaria para realizar los análisis.

# Librerías

```{r}
pacman::p_load(dplyr,
               openxlsx,
               haven,
               sjPlot)
```

# Data

```{r}
data <- read.xlsx("../input/data/original/Base_Final_Estudiantes_1644_20_01_2020.v2+posoct.xlsx", 1)
data2009 <- read_dta("../input/data/original/isachlc2.dta")
dataprof <- read_dta("../input/data/original/Base Docentes v2.dta")
dataapod <- read_dta("../input/data/original/Base Apoderados v2.dta")
```

# Información de la sesión

```{r}
print(paste("R", getRversion()))
print("*** Versiones de librerías")
for (package_name in sort(loadedNamespaces())) {
    print(paste(package_name, packageVersion(package_name)))
}
```

# Preparación
## Data estudiantes
```{r}
sjPlot::view_df(data)
# Conocimiento cívico: análisis descriptivo
## P1
data$P1[data$P1==5]<-NA
data$P1[data$P1==9]<-NA
## P2
data$P2[data$P2==5]<-NA
data$P2[data$P2==9]<-NA
## P3
data$P3[data$P3==5]<-NA
data$P3[data$P3==9]<-NA
## P4
data$P4[data$P4==5]<-NA
data$P4[data$P4==9]<-NA
## P5
data$P5[data$P5==5]<-NA
data$P5[data$P5==9]<-NA
## P6
data$P6[data$P6==5]<-NA
data$P6[data$P6==9]<-NA
## P7
data$P7[data$P7==7]<-NA
data$P7[data$P7==9]<-NA
## P8
data$P8[data$P8==5]<-NA
data$P8[data$P8==9]<-NA
## P9
data$P9[data$P9==5]<-NA
data$P9[data$P9==9]<-NA
## P10
data$P10[data$P10==6]<-NA
data$P10[data$P10==9]<-NA
## P11
data$P11[data$P11==5]<-NA
data$P11[data$P11==9]<-NA
## P12
data$P12[data$P12==5]<-NA
data$P12[data$P12==9]<-NA
## P13
data$P13[data$P13==5]<-NA
data$P13[data$P13==9]<-NA
## P14
data$P14[data$P14==5]<-NA
data$P14[data$P14==9]<-NA

# Conocimiento cívico: comparación iccs 2009 y estudio 2019
## P1
data$P1[data$P1==5]<-NA
data$P1[data$P1==9]<-NA
data2009$CI2RDM2[data2009$CI2RDM2==6]<-NA
data2009$CI2RDM2[data2009$CI2RDM2==7]<-NA
data2009$CI2RDM2[data2009$CI2RDM2==9]<-NA
data$P1_A = ifelse(data$P1==1,100,0)
data$P1_B = ifelse(data$P1==2,100,0)
data$P1_C = ifelse(data$P1==3,100,0)
data$P1_D = ifelse(data$P1==4,100,0)
data2009$CI2RDM2_A = ifelse(data2009$CI2RDM2==1,100,0)
data2009$CI2RDM2_B = ifelse(data2009$CI2RDM2==2,100,0)
data2009$CI2RDM2_C = ifelse(data2009$CI2RDM2==3,100,0)
data2009$CI2RDM2_D = ifelse(data2009$CI2RDM2==4,100,0)
## P2
data$P2[data$P2==5]<-NA
data$P2[data$P2==9]<-NA
data2009$CI128M1[data2009$CI128M1==6]<-NA
data2009$CI128M1[data2009$CI128M1==7]<-NA
data2009$CI128M1[data2009$CI128M1==9]<-NA
data$P2_A = ifelse(data$P2==1,100,0)
data$P2_B = ifelse(data$P2==2,100,0)
data$P2_C = ifelse(data$P2==3,100,0)
data$P2_D = ifelse(data$P2==4,100,0)
data2009$CI128M1_A = ifelse(data2009$CI128M1==1,100,0)
data2009$CI128M1_B = ifelse(data2009$CI128M1==2,100,0)
data2009$CI128M1_C = ifelse(data2009$CI128M1==3,100,0)
data2009$CI128M1_D = ifelse(data2009$CI128M1==4,100,0)
## P3
data$P3[data$P3==5]<-NA
data$P3[data$P3==9]<-NA
data2009$CI110M1[data2009$CI110M1==6]<-NA
data2009$CI110M1[data2009$CI110M1==7]<-NA
data2009$CI110M1[data2009$CI110M1==9]<-NA
data$P3_A = ifelse(data$P3==1,100,0)
data$P3_B = ifelse(data$P3==2,100,0)
data$P3_C = ifelse(data$P3==3,100,0)
data$P3_D = ifelse(data$P3==4,100,0)
data2009$CI110M1_A = ifelse(data2009$CI110M1==1,100,0)
data2009$CI110M1_B = ifelse(data2009$CI110M1==2,100,0)
data2009$CI110M1_C = ifelse(data2009$CI110M1==3,100,0)
data2009$CI110M1_D = ifelse(data2009$CI110M1==4,100,0)
## P4
data$P4[data$P4==5]<-NA
data$P4[data$P4==9]<-NA
data2009$CI113M1[data2009$CI113M1==6]<-NA
data2009$CI113M1[data2009$CI113M1==7]<-NA
data2009$CI113M1[data2009$CI113M1==9]<-NA
data$P4_A = ifelse(data$P4==1,100,0)
data$P4_B = ifelse(data$P4==2,100,0)
data$P4_C = ifelse(data$P4==3,100,0)
data$P4_D = ifelse(data$P4==4,100,0)
data2009$CI113M1_A = ifelse(data2009$CI113M1==1,100,0)
data2009$CI113M1_B = ifelse(data2009$CI113M1==2,100,0)
data2009$CI113M1_C = ifelse(data2009$CI113M1==3,100,0)
data2009$CI113M1_D = ifelse(data2009$CI113M1==4,100,0)
## P5 
data$P5[data$P5==5]<-NA
data$P5[data$P5==9]<-NA
data2009$CI129M1[data2009$CI129M1==6]<-NA
data2009$CI129M1[data2009$CI129M1==7]<-NA
data2009$CI129M1[data2009$CI129M1==9]<-NA
data$P5_A = ifelse(data$P5==1,100,0)
data$P5_B = ifelse(data$P5==2,100,0)
data$P5_C = ifelse(data$P5==3,100,0)
data$P5_D = ifelse(data$P5==4,100,0)
data2009$CI129M1_A = ifelse(data2009$CI129M1==1,100,0)
data2009$CI129M1_B = ifelse(data2009$CI129M1==2,100,0)
data2009$CI129M1_C = ifelse(data2009$CI129M1==3,100,0)
data2009$CI129M1_D = ifelse(data2009$CI129M1==4,100,0)
## P6
data$P6[data$P6==5]<-NA
data$P6[data$P6==9]<-NA
data2009$CI137M1[data2009$CI137M1==6]<-NA
data2009$CI137M1[data2009$CI137M1==7]<-NA
data2009$CI137M1[data2009$CI137M1==9]<-NA
data$P6_A = ifelse(data$P6==1,100,0)
data$P6_B = ifelse(data$P6==2,100,0)
data$P6_C = ifelse(data$P6==3,100,0)
data$P6_D = ifelse(data$P6==4,100,0)
data2009$CI137M1_A = ifelse(data2009$CI137M1==1,100,0)
data2009$CI137M1_B = ifelse(data2009$CI137M1==2,100,0)
data2009$CI137M1_C = ifelse(data2009$CI137M1==3,100,0)
data2009$CI137M1_D = ifelse(data2009$CI137M1==4,100,0)

##Escala de conocimiento civico
data$c1 <- ifelse(data$P1==4,1,0) ## 0 = respuesta incorrecta y 1 = respuesta correcta
data$c2 <- ifelse(data$P2==4,1,0)
data$c3 <- ifelse(data$P3==4,1,0)
data$c4 <- ifelse(data$P4==2,1,0)
data$c5 <- ifelse(data$P5==3,1,0)
data$c6 <- ifelse(data$P6==4,1,0)
data$c7 <- ifelse(data$P7==3,1,0)
data$c8 <- ifelse(data$P8==2,1,0)
data$c9 <- ifelse(data$P9==1,1,0)
data$Conocimiento_civico_conceptual= as.numeric(data$c1 + data$c2 + data$c3 + data$c4 + data$c5 + data$c6 + data$c7 + data$c8) 
data$c7 <- ifelse(data$P7==3,1,0)
data$c8 <- ifelse(data$P8==2,1,0)
data$c9 <- ifelse(data$P9==1,1,0)
data$c10 <- ifelse(data$P10==3,1,0)
data$c11 <- ifelse(data$P11==1,1,0)
data$c12 <- ifelse(data$P12==3,1,0)
data$c13 <- ifelse(data$P13==3,1,0)
data$c14 <- ifelse(data$P14==4,1,0)
data$Conocimiento_civico_factual= as.numeric(data$c9 + data$c10 + data$c11 + + data$c12 + data$c13 + data$c14)

## Formación ciudadana
### Aspectos relevantes
data$P52A[data$P52A==9]<-NA
data$P52B[data$P52B==5]<-NA
data$P52B[data$P52B==9]<-NA
data$P52C[data$P52C==5]<-NA
data$P52C[data$P52C==9]<-NA
data$P52D[data$P52D==5]<-NA
data$P52D[data$P52D==9]<-NA
data$P52E[data$P52E==5]<-NA
data$P52E[data$P52E==9]<-NA
### Aspecto más relevante de la formación ciudadana
data$P53[data$P53=="AB"]<-NA
data$P53[data$P53=="AD"]<-NA
data$P53[data$P53=="AE"]<-NA
data$P53[data$P53=="BD"]<-NA
data$P53[data$P53=="EA"]<-NA
data$P53[data$P53=="ED"]<-NA
data$P53[data$P53=="NR"]<-NA
### Quién juega el rol más importante en cada uno de esos aspectos
data$P55A[data$P55A==4]<-NA
data$P55A[data$P55A==9]<-NA
data$P55B[data$P55B==4]<-NA
data$P55B[data$P55B==9]<-NA
data$P55C[data$P55C==4]<-NA
data$P55C[data$P55C==9]<-NA
data$P55D[data$P55D==4]<-NA
data$P55D[data$P55D==9]<-NA
data$P55E[data$P55E==4]<-NA
data$P55E[data$P55E==9]<-NA

## Interés en la política
data$P43D[data$P43D==5]<-NA
data$P43D[data$P43D==9]<-NA
## Interés en la desigualdad social
data$P43A[data$P43A==5]<-NA
data$P43A[data$P43A==9]<-NA
## Interés en el medioambiente
data$P43B[data$P43B==5]<-NA
data$P43B[data$P43B==9]<-NA
## Interés en la igualdad de género
data$P43C[data$P43C==5]<-NA
data$P43C[data$P43C==9]<-NA

## Satisfacción con la democracia
data$P15[data$P15==5]<-NA
data$P15[data$P15==9]<-NA

## Actitudes y creencias autoritarias
data$P21A[data$P21A==5]<-NA
data$P21A[data$P21A==9]<-NA
data$P21B[data$P21B==5]<-NA
data$P21B[data$P21B==9]<-NA
data$P21C[data$P21C==5]<-NA
data$P21C[data$P21C==9]<-NA
data$P21D[data$P21D==5]<-NA
data$P21D[data$P21D==9]<-NA
data$P21E[data$P21E==5]<-NA
data$P21E[data$P21E==9]<-NA
data$P21F[data$P21F==5]<-NA
data$P21F[data$P21F==9]<-NA
data$P21G[data$P21G==5]<-NA
data$P21G[data$P21G==9]<-NA
data$P21H[data$P21H==5]<-NA
data$P21H[data$P21H==9]<-NA
data$P21I[data$P21I==5]<-NA
data$P21I[data$P21I==9]<-NA

## Confianza en instituciones
data$P22A[data$P22A==5]<-NA
data$P22A[data$P22A==9]<-NA
data$P22B[data$P22B==5]<-NA
data$P22B[data$P22B==9]<-NA
data$P22C[data$P22C==5]<-NA
data$P22C[data$P22C==9]<-NA
data$P22D[data$P22D==5]<-NA
data$P22D[data$P22D==9]<-NA
data$P22E[data$P22E==5]<-NA
data$P22E[data$P22E==9]<-NA
data$P22F[data$P22F==5]<-NA
data$P22F[data$P22F==9]<-NA

## Participación formal
data$P30A[data$P30A==3]<-NA
data$P30A[data$P30A==9]<-NA
data$P30B[data$P30B==9]<-NA
data$P30C[data$P30C==3]<-NA
data$P30C[data$P30C==9]<-NA
data$P31A[data$P31A==9]<-NA
data$P31B[data$P31B==9]<-NA
data$P31C[data$P31C==9]<-NA
## Participación activista
data$P30D[data$P30D==3]<-NA
data$P30D[data$P30D==9]<-NA
data$P30E[data$P30E==3]<-NA
data$P30E[data$P30E==9]<-NA
data$P30F[data$P30F==3]<-NA
data$P30F[data$P30F==9]<-NA
data$P33A[data$P33A==3]<-NA
data$P33A[data$P33A==9]<-NA
data$P33B[data$P33B==3]<-NA
data$P33B[data$P33B==9]<-NA
data$P33C[data$P33C==3]<-NA
data$P33C[data$P33C==9]<-NA
data$P33D[data$P33D==3]<-NA
data$P33D[data$P33D==9]<-NA
## Participación comunitaria
data$P30G[data$P30G==3]<-NA
data$P30G[data$P30G==9]<-NA
data$P30H[data$P30H==3]<-NA
data$P30H[data$P30H==9]<-NA
data$P30I[data$P30I==3]<-NA
data$P30I[data$P30I==9]<-NA
data$P33E[data$P33E==3]<-NA
data$P33E[data$P33E==9]<-NA
data$P33F[data$P33F==3]<-NA
data$P33F[data$P33F==9]<-NA
data$P33G[data$P33G==3]<-NA
data$P33G[data$P33G==9]<-NA

## Sexo
data$P58[data$P58==4]<-NA
data$P58[data$P58==9]<-NA
data_muj = data %>%  filter(P58 == 2) %>% as.data.frame()
data_hom = data %>%  filter(P58 == 1) %>% as.data.frame()

## Nivel educativo más alto de los padres
data$P66[data$P66==8]<-NA #ed. madre
data$P66[data$P66==9]<-NA
data$P67[data$P67==8]<-NA #ed. padre
data$P67[data$P67==9]<-NA
data$edpadres <- ifelse(data$P66>data$P67,data$P66,data$P67)
data_binc = data %>%  filter(edpadres == 1) %>% as.data.frame()
data_bas = data %>%  filter(edpadres == 2) %>% as.data.frame()
data_media = data %>%  filter(edpadres == 3) %>% as.data.frame()
data_tec = data %>%  filter(edpadres == 4) %>% as.data.frame()
data_univ = data %>%  filter(edpadres == 5) %>% as.data.frame()

## Separación entre regiones
data_antofa = data %>%  filter(REGION == 2) %>% as.data.frame()
data_maule = data %>%  filter(REGION == 7) %>% as.data.frame()
data_metro = data %>%  filter(REGION == 13) %>% as.data.frame()

## Dependencia escolar
data_mun = data %>%  filter(Dependencia == 1) %>% as.data.frame()
data_sub = data %>%  filter(Dependencia == 2) %>% as.data.frame()
data_priv = data %>%  filter(Dependencia == 3) %>% as.data.frame()
```
## Data docentes
```{r}
sjPlot::view_df(dataprof)
# Importancia de distintos aspectos en la formación ciudadana
dataprof$P27A[dataprof$P27A==9]<-NA
dataprof$P27B[dataprof$P27B==9]<-NA
dataprof$P27C[dataprof$P27C==9]<-NA
dataprof$P27D[dataprof$P27D==9]<-NA
dataprof$P27E[dataprof$P27E==9]<-NA

# Aspecto más relevante en la formación ciudadana
dataprof$P28[dataprof$P28=="NR"]<-NA

# Quién juega el rol más importante en los distintos aspectos de la formación ciudadana
dataprof$P30A[dataprof$P30A==9]<-NA
dataprof$P30B[dataprof$P30B==9]<-NA
dataprof$P30C[dataprof$P30C==9]<-NA
dataprof$P30D[dataprof$P30D==9]<-NA
dataprof$P30E[dataprof$P30E==9]<-NA

# Interés en la política
dataprof$P11[dataprof$P11==9]<-NA

# Actitudes y creencias autoritarias
dataprof$P18A[dataprof$P18A==9]<-NA
dataprof$P18B[dataprof$P18B==9]<-NA
dataprof$P18C[dataprof$P18C==9]<-NA
dataprof$P18D[dataprof$P18D==9]<-NA
dataprof$P18E[dataprof$P18E==9]<-NA
dataprof$P18F[dataprof$P18F==9]<-NA
dataprof$P18G[dataprof$P18G==9]<-NA
dataprof$P18H[dataprof$P18H==9]<-NA
dataprof$P18I[dataprof$P18I==9]<-NA
```
## Data apoderados
```{r}
sjPlot::view_df(dataapod)
# Importancia de distintos aspectos en la formación ciudadana
dataapod$P34A[dataapod$P34A==9]<-NA
dataapod$P34B[dataapod$P34B==9]<-NA
dataapod$P34C[dataapod$P34C==9]<-NA
dataapod$P34D[dataapod$P34D==9]<-NA
dataapod$P34E[dataapod$P34E==9]<-NA

# Aspecto más relevante en la formación ciudadana
dataapod$P35[dataapod$P35=="AB"]<-NA
dataapod$P35[dataapod$P35=="AE"]<-NA
dataapod$P35[dataapod$P35=="NR"]<-NA

# Quién juega el rol más importante en los distintos aspectos de la formación ciudadana
dataapod$P37A[dataapod$P37A==9]<-NA
dataapod$P37B[dataapod$P37B==9]<-NA
dataapod$P37C[dataapod$P37C==9]<-NA
dataapod$P37D[dataapod$P37D==9]<-NA
dataapod$P37E[dataapod$P37E==9]<-NA

# Interés en la política
dataapod$P38D[dataapod$P38D==9]<-NA
# Interés en la desigualdad social
dataapod$P38A[dataapod$P38A==9]<-NA
# Interés en el medioambiente
dataapod$P38B[dataapod$P38B==9]<-NA
# Interés en la igualdad de género
dataapod$P38C[dataapod$P38C==9]<-NA

# Satisfacción con la democracia
dataapod$P3[dataapod$P3==9]<-NA

# Actitudes y creencias autoritarias
dataapod$P5A[dataapod$P5A==9]<-NA
dataapod$P5B[dataapod$P5B==9]<-NA
dataapod$P5C[dataapod$P5C==9]<-NA
dataapod$P5D[dataapod$P5D==9]<-NA
dataapod$P5E[dataapod$P5E==9]<-NA
dataapod$P5F[dataapod$P5F==9]<-NA
dataapod$P5G[dataapod$P5G==9]<-NA
dataapod$P5H[dataapod$P5H==9]<-NA
dataapod$P5I[dataapod$P5I==9]<-NA
```
# Data proc
```{r}
save(data, file= "../input/data/proc/data.Rdata")
save(data2009, file= "../input/data/proc/data2009.Rdata")

save(data_antofa, file= "../input/data/proc/data_antofa.Rdata")
save(data_maule, file= "../input/data/proc/data_maule.Rdata")
save(data_metro, file= "../input/data/proc/data_metro.Rdata")

save(data_mun, file= "../input/data/proc/data_mun.Rdata")
save(data_sub, file= "../input/data/proc/data_sub.Rdata")
save(data_priv, file= "../input/data/proc/data_priv.Rdata")

save(data_muj, file= "../input/data/proc/data_muj.Rdata")
save(data_hom, file= "../input/data/proc/data_hom.Rdata")

save(data_binc, file= "../input/data/proc/data_binc.Rdata")
save(data_bas, file= "../input/data/proc/data_bas.Rdata")
save(data_media, file= "../input/data/proc/data_media.Rdata")
save(data_tec, file= "../input/data/proc/data_tec.Rdata")
save(data_univ, file= "../input/data/proc/data_univ.Rdata")

save(dataprof, file= "../input/data/proc/data_prof.Rdata")
save(dataapod, file= "../input/data/proc/data_apod.Rdata")
```

